### ISSUE TITLE
Mod xp doesn't works on Multiplayer.

### ISSUE THREAD

**Issue by Gumpiboi** [thetrueoneshots/PyroProgression#1]
Mod is great so far. Seeing the xp bar really fills my heart with joy.
But one thing that is missing is the multiplayer xp compability.

Only the host gets xp and only when he last hits the enemy.
If a non-host gets the last hit, no xp is given. 
A friend and I were playing together and we had to switch now and then so our level difference wouldn't be too big.

**Comment by thetrueoneshots** [comment]
I am working on multiplayer support for the mod currently. It is for now single-player support only. My latest release does add a `/recenter` command that allows you to configure your region with the other player. For XP sharing I will still have to find a solution :)

**Comment by thetrueoneshots** [comment]
@Gumpiboi I have fixed XP sharing with the latest version (`v.1.3`) of the pyroprog mod.
