### ISSUE TITLE
Gear cost is not scaling

### ISSUE THREAD

**Issue by Xanirus** [thetrueoneshots/PyroProgression#10]
It doesn't seem like the gear's cost (both buying and selling) is scaling at all, despite it being listed as a mod mechanic.

**Comment by Xanirus** [comment]
In retrospect, the gold cost is scaling, at least for buying.  I guess I was just expecting much bigger numbers to compensate for the huge gold drops, but again this is the same save that has gone through all the iterations of the mod; I was dominating and getting so much gold in 1.3.

The selling prices I'm not sure if they're scaling or not though.  They probably are, but there's so much fluctuation it's hard to tell.

**Comment by thetrueoneshots** [comment]
Hey thanks for the feedback! Indeed gold costs are scaling, but very slowly. Maybe I should look into increasing the costs of gear more. Selling price is a built-in cubeworld function that calls the gear cost function. So as long as the gear cost scales, the gear selling price will automatically scale as well. In Cube World vanilla, Wollay uses a root function to calculate the selling price, which means the selling price of items is way lower than their buying price. This difference only increases as the buying price of the items go up.

For the next version of PyroProgression I will look into improving the gold cost of buying items and scale it better with the enemy and gold scalings.
