### ISSUE TITLE
Xp Gain suggestion

### ISSUE THREAD

**Issue by PyroThunderzz** [thetrueoneshots/PyroProgression#16]
Killing a level 4 one star enemy currently gives you 1 xp but it really should give 4 xp instead (the xp system of 1.1 would be really nice to bring back because it honestly felt the most balanced)

**Comment by thetrueoneshots** [comment]
Fixed it with commit [8440eaf] (https://github.com/thetrueoneshots/PyroProgression/commit/8440eaff27c6776874c27d7bf0384af365250187) Rolled it back to the v.1.1 progression!
