### ISSUE TITLE
You can instantly get lvl 100+ by flying far away to another village

### ISSUE THREAD

**Issue by mmds1** [thetrueoneshots/PyroProgression#20]
you can buy bombs in the store and destroy them, the bombs give you XP and increase in level the further away from the center of your spawn, increasing the XP they give.

**Comment by thetrueoneshots** [comment]
Yes you can! It an interesting way to levelup, but I guess thats for speedruns? You think this is something that should be patched?

**Comment by mmds1** [comment]
When you know that something like this exists, its kinda boring to play the game normally, feels like you're levelling up in the slow/wrong way. The fun is in finding the fastest but fair way to level up
