### ISSUE TITLE
gear stats issue

### ISSUE THREAD

**Issue by teoxihuitl** [thetrueoneshots/PyroProgression#8]
all my gear has abnormally high stats and takes level 2mil to equip even the base starting gear

**Comment by thetrueoneshots** [comment]
Did you do a `/recenter` when playing with a friend by any chance? Or using any other progression mods?

**Comment by teoxihuitl** [comment]
I dont do a /recenter ill try that out. And i am using other progression mods but i already checked if they were the problem by uninstalling and just running the mega and pyro but the problem still persists but ill try the /recenter and get back to you

**Comment by teoxihuitl** [comment]
I tried /recenter but the stats and stat levels are still super high. The items appear regular on the ground but right when they enter my inventory they get altered and the gear level increases to 2mil and i cant use it

**Comment by teoxihuitl** [comment]
I fixed it

**Comment by thetrueoneshots** [comment]
Good to hear you fixed it. I am guessing the solution was using the latest version of the pyroprogression?

**Comment by teoxihuitl** [comment]
It was actually using /setcenter and then using /recenter
