### ISSUE TITLE
stat issue

### ISSUE THREAD

**Issue by teoxihuitl** [thetrueoneshots/PyroProgression#9]
for some reason amulets and rings have no stats they are just simply there is that how its supposed to be or should they have stats?

**Comment by thetrueoneshots** [comment]
Is this still the issue with the latest version (`v.1.4`) of the pyroprogression mod? I will look into it when I am working on the next version.

**Comment by thetrueoneshots** [comment]
I created issue #11 for that and will fix it. Thanks for letting me know.
